# Generated by Django 3.2.13 on 2022-07-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcategory',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
