# Generated by Django 3.2.13 on 2022-07-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account_type',
            field=models.CharField(choices=[('Debit', '지출'), ('Credit', '수입')], default='Debit', max_length=10),
        ),
    ]
