# Generated by Django 3.2.13 on 2022-07-08 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0003_alter_accountdetail_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='account_books.accountbook', verbose_name='가계부'),
        ),
    ]
